FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    python3 \
    py3-setuptools

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

EXPOSE 3000

CMD ["npm", "start"]